const polandStats = {
  _id: '64770a783b221c821a022387',
  statsDate: '2023-05-31T08:51:04.155Z',
  statsDay: '31-05-2023',
  sourceDate: '2023.05.31 10:30',
  totalInfected: 6516915,
  newlyInfected: 6326599,
  reInfected: 190316,
  deceased: 119610,
  recovered: 5335777,
  dailyTotalInfected: 62,
  dailyNewlyInfected: 50,
  dailyReInfected: 12,
  dailyTested: 2436,
  dailyPositiveTests: 75,
  dailyDeceased: 0,
  dailyDeceasedCovidOnly: 0,
  dailyDeceasedCovidWithOtherDiseases: 0,
  dailyRecovered: 0,
  dailyQuarantine: 0,
  regions: [
    {
      name: 'opolskie',
      population: 986506,
      deceased: 0,
      deceasedCovidOnly: 0,
      deceasedWithOtherDiseases: 0,
      quarantied: 0,
      testsDone: 172,
      testsPositive: 0,
      testsNegative: 172,
      testsFromPOZ: 1,
      testsOthers: 0,
      recovered: 0,
      reInfected: 0,
      totalInfected: 0,
      newlyInfectedPer10k: 0,
      reInfectedPer10k: 0,
      totalInfectedPer10k: 0,
      newlyInfected: 0
    },
    {
      name: 'świętokrzyskie',
      population: 1241546,
      deceased: 0,
      deceasedCovidOnly: 0,
      deceasedWithOtherDiseases: 0,
      quarantied: 0,
      testsDone: 60,
      testsPositive: 5,
      testsNegative: 55,
      testsFromPOZ: 0,
      testsOthers: 0,
      recovered: 0,
      reInfected: 0,
      totalInfected: 2,
      newlyInfectedPer10k: 2,
      reInfectedPer10k: 0,
      totalInfectedPer10k: 2,
      newlyInfected: 2
    },
    {
      name: 'kujawsko-pomorskie',
      population: 2077775,
      deceased: 0,
      deceasedCovidOnly: 0,
      deceasedWithOtherDiseases: 0,
      quarantied: 0,
      testsDone: 90,
      testsPositive: 4,
      testsNegative: 86,
      testsFromPOZ: 16,
      testsOthers: 0,
      recovered: 0,
      reInfected: 1,
      totalInfected: 4,
      newlyInfectedPer10k: 1,
      reInfectedPer10k: 0,
      totalInfectedPer10k: 2,
      newlyInfected: 3
    },
    {
      name: 'mazowieckie',
      population: 5403412,
      deceased: 0,
      deceasedCovidOnly: 0,
      deceasedWithOtherDiseases: 0,
      quarantied: 0,
      testsDone: 492,
      testsPositive: 5,
      testsNegative: 487,
      testsFromPOZ: 24,
      testsOthers: 0,
      recovered: 0,
      reInfected: 1,
      totalInfected: 3,
      newlyInfectedPer10k: 0,
      reInfectedPer10k: 0,
      totalInfectedPer10k: 1,
      newlyInfected: 2
    },
    {
      name: 'pomorskie',
      population: 2333523,
      deceased: 0,
      deceasedCovidOnly: 0,
      deceasedWithOtherDiseases: 0,
      quarantied: 0,
      testsDone: 116,
      testsPositive: 4,
      testsNegative: 112,
      testsFromPOZ: 8,
      testsOthers: 0,
      recovered: 0,
      reInfected: 1,
      totalInfected: 3,
      newlyInfectedPer10k: 1,
      reInfectedPer10k: 0,
      totalInfectedPer10k: 1,
      newlyInfected: 2
    },
    {
      name: 'śląskie',
      population: 4533565,
      deceased: 0,
      deceasedCovidOnly: 0,
      deceasedWithOtherDiseases: 0,
      quarantied: 0,
      testsDone: 240,
      testsPositive: 11,
      testsNegative: 229,
      testsFromPOZ: 32,
      testsOthers: 0,
      recovered: 0,
      reInfected: 0,
      totalInfected: 10,
      newlyInfectedPer10k: 2,
      reInfectedPer10k: 0,
      totalInfectedPer10k: 2,
      newlyInfected: 10
    },
    {
      name: 'warmińsko-mazurskie',
      population: 1428983,
      deceased: 0,
      deceasedCovidOnly: 0,
      deceasedWithOtherDiseases: 0,
      quarantied: 0,
      testsDone: 126,
      testsPositive: 4,
      testsNegative: 122,
      testsFromPOZ: 17,
      testsOthers: 0,
      recovered: 0,
      reInfected: 2,
      totalInfected: 3,
      newlyInfectedPer10k: 1,
      reInfectedPer10k: 1,
      totalInfectedPer10k: 2,
      newlyInfected: 1
    },
    {
      name: 'zachodniopomorskie',
      population: 1701030,
      deceased: 0,
      deceasedCovidOnly: 0,
      deceasedWithOtherDiseases: 0,
      quarantied: 0,
      testsDone: 90,
      testsPositive: 6,
      testsNegative: 83,
      testsFromPOZ: 19,
      testsOthers: 1,
      recovered: 0,
      reInfected: 0,
      totalInfected: 6,
      newlyInfectedPer10k: 4,
      reInfectedPer10k: 0,
      totalInfectedPer10k: 4,
      newlyInfected: 6
    },
    {
      name: 'dolnośląskie',
      population: 2901225,
      deceased: 0,
      deceasedCovidOnly: 0,
      deceasedWithOtherDiseases: 0,
      quarantied: 0,
      testsDone: 98,
      testsPositive: 4,
      testsNegative: 94,
      testsFromPOZ: 11,
      testsOthers: 0,
      recovered: 0,
      reInfected: 3,
      totalInfected: 4,
      newlyInfectedPer10k: 0,
      reInfectedPer10k: 1,
      totalInfectedPer10k: 1,
      newlyInfected: 1
    },
    {
      name: 'wielkopolskie',
      population: 3493969,
      deceased: 0,
      deceasedCovidOnly: 0,
      deceasedWithOtherDiseases: 0,
      quarantied: 0,
      testsDone: 76,
      testsPositive: 6,
      testsNegative: 70,
      testsFromPOZ: 13,
      testsOthers: 0,
      recovered: 0,
      reInfected: 2,
      totalInfected: 6,
      newlyInfectedPer10k: 1,
      reInfectedPer10k: 1,
      totalInfectedPer10k: 2,
      newlyInfected: 4
    },
    {
      name: 'łódzkie',
      population: 2466322,
      deceased: 0,
      deceasedCovidOnly: 0,
      deceasedWithOtherDiseases: 0,
      quarantied: 0,
      testsDone: 81,
      testsPositive: 0,
      testsNegative: 80,
      testsFromPOZ: 7,
      testsOthers: 1,
      recovered: 0,
      reInfected: 0,
      totalInfected: 0,
      newlyInfectedPer10k: 0,
      reInfectedPer10k: 0,
      totalInfectedPer10k: 0,
      newlyInfected: 0
    },
    {
      name: 'podlaskie',
      population: 1181533,
      deceased: 0,
      deceasedCovidOnly: 0,
      deceasedWithOtherDiseases: 0,
      quarantied: 0,
      testsDone: 72,
      testsPositive: 5,
      testsNegative: 67,
      testsFromPOZ: 11,
      testsOthers: 0,
      recovered: 0,
      reInfected: 0,
      totalInfected: 2,
      newlyInfectedPer10k: 2,
      reInfectedPer10k: 0,
      totalInfectedPer10k: 2,
      newlyInfected: 2
    },
    {
      name: 'małopolskie',
      population: 3400577,
      deceased: 0,
      deceasedCovidOnly: 0,
      deceasedWithOtherDiseases: 0,
      quarantied: 0,
      testsDone: 124,
      testsPositive: 7,
      testsNegative: 117,
      testsFromPOZ: 21,
      testsOthers: 0,
      recovered: 0,
      reInfected: 0,
      totalInfected: 6,
      newlyInfectedPer10k: 2,
      reInfectedPer10k: 0,
      totalInfectedPer10k: 2,
      newlyInfected: 6
    },
    {
      name: 'lubuskie',
      population: 1014548,
      deceased: 0,
      deceasedCovidOnly: 0,
      deceasedWithOtherDiseases: 0,
      quarantied: 0,
      testsDone: 28,
      testsPositive: 2,
      testsNegative: 26,
      testsFromPOZ: 3,
      testsOthers: 0,
      recovered: 0,
      reInfected: 0,
      totalInfected: 2,
      newlyInfectedPer10k: 2,
      reInfectedPer10k: 0,
      totalInfectedPer10k: 2,
      newlyInfected: 2
    },
    {
      name: 'podkarpackie',
      population: 2129015,
      deceased: 0,
      deceasedCovidOnly: 0,
      deceasedWithOtherDiseases: 0,
      quarantied: 0,
      testsDone: 145,
      testsPositive: 3,
      testsNegative: 142,
      testsFromPOZ: 4,
      testsOthers: 0,
      recovered: 0,
      reInfected: 0,
      totalInfected: 2,
      newlyInfectedPer10k: 1,
      reInfectedPer10k: 0,
      totalInfectedPer10k: 1,
      newlyInfected: 2
    },
    {
      name: 'lubelskie',
      population: 2117619,
      deceased: 0,
      deceasedCovidOnly: 0,
      deceasedWithOtherDiseases: 0,
      quarantied: 0,
      testsDone: 298,
      testsPositive: 7,
      testsNegative: 290,
      testsFromPOZ: 9,
      testsOthers: 1,
      recovered: 0,
      reInfected: 1,
      totalInfected: 7,
      newlyInfectedPer10k: 3,
      reInfectedPer10k: 0,
      totalInfectedPer10k: 3,
      newlyInfected: 6
    }
  ],
  updated: '2023-05-31T08:51:04.476Z',
  __v: 0
}

const globalStats = {
  get: 'statistics',
  parameters: [],
  errors: [],
  results: 238,
  response: [],
}

const globalStatsResponse = {
  continent: 'Europe',
  country: 'Isle-of-Man',
  population: 85732,
  cases: {
    new: null,
    active: null,
    critical: null,
    recovered: null,
    '1M_pop': '443335',
    total: 38008
  },
  deaths: { new: null, '1M_pop': '1353', total: 116 },
  tests: { '1M_pop': '1758422', total: 150753 },
  day: '2023-06-07',
  time: '2023-06-07T19:00:08+00:00'
}