export const POLAND_MAIN_STATS_NAMES = {
  statsDate: 'Date',
  statsDay: 'Dzień',
  sourceDate: 'Data',
  totalInfected: 'Wszyscy zainfekowani',
  newlyInfected: 'Nowi zainfekowani',
  reInfected: 'Ponownie zainfekowani',
  deceased: 'Zgony',
  recovered: 'Ozdrowienia',
  dailyTotalInfected: 'Wszyscy zainfekowani',
  dailyNewlyInfected: 'Nowi zainfekowani',
  dailyReInfected: 'Ponownie zainfekowani',
  dailyTested: 'Wykonane testy',
  dailyPositiveTests: 'Testy pozytywne',
  dailyDeceased: 'Zgony',
  dailyDeceasedCovidOnly: 'Zgony wyłącznie z powodu COVID-19',
  dailyDeceasedCovidWithOtherDiseases: 'Zgony z chorobami współistniejącymi',
  dailyRecovered: 'Wyzdrowienia',
  dailyQuarantine: 'Kwarantanna'
};
